<?php
namespace Opencart\Catalog\Controller\Extension\Ohbono\Module;

class WalletPayment extends \Opencart\System\Engine\Controller
{
    /**
     * Final wallet payment endpoint.
     *
     * The checkout/order controller should call the service directly when
     * possible. This endpoint exists as a thin integration adapter.
     */
    public function capture(): void
    {
        if (!$this->customer->isLogged()) {
            $this->json([
                'success' => false,
                'error' => 'Customer login is required.'
            ]);
            return;
        }

        $order_id = (int)(
            $this->request->post['order_id'] ?? 0
        );

        $order_total = round(
            max(
                0.0,
                (float)($this->request->post['order_total'] ?? 0)
            ),
            4
        );

        $requested_amount = round(
            max(
                0.0,
                (float)($this->request->post['amount'] ?? 0)
            ),
            4
        );

        /*
         * The reference must be generated by the trusted checkout layer.
         * Do not use a client-generated random value as the only protection
         * against replay.
         */
        $reference = trim((string)(
            $this->request->post['reference'] ?? ''
        ));

        if ($order_id <= 0 ||
            $order_total <= 0 ||
            $requested_amount <= 0 ||
            $reference === '') {
            $this->json([
                'success' => false,
                'error' => 'Incomplete wallet payment request.'
            ]);
            return;
        }

        try {
            $service =
                new \OhbonoWalletPaymentService($this->db);

            $result =
                $service->authorizeAndCapture(
                    (int)$this->customer->getId(),
                    $order_total,
                    $requested_amount,
                    $reference,
                    $order_id
                );

            $this->json([
                'success' => true,
                'transaction_id' =>
                    $result['transaction_id'],
                'amount' =>
                    $result['amount'],
                'balance_after' =>
                    $result['balance_after'],
                'idempotent' =>
                    $result['idempotent']
            ]);
        } catch (\Throwable $e) {
            $this->json([
                'success' => false,
                'error' => $e->getMessage()
            ]);
        }
    }

    private function json(array $data): void
    {
        $this->response->addHeader(
            'Content-Type: application/json'
        );

        $this->response->setOutput(
            json_encode($data)
        );
    }
}
